using ProjetoTinta.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace ProjetoTinta
{
    /// <summary>
    /// Interaction logic for Listar.xaml
    /// </summary>
    public partial class Listar : Window
    {
        TintaDao tDao;
        public Listar()
        {
            InitializeComponent();
            tDao = new TintaDao();
            dgTintas.ItemsSource = tDao.listar();

        }

        private void dgTintas_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgTintas.Columns[0].Width = 150;
            dgTintas.Columns[1].Width = 150;
            dgTintas.Columns[2].Width = 150;
        }
    }
}
